### ISSUE TITLE
Mismatch in firms and establishment employment size category

### ISSUE THREAD

**Issue by goreaditya** [RSGInc/rFirm#41]
Currently the relocation and re-scaling of establishment employment producers new employment size category for establishments that breaks it links to corresponding firms with specific firm employment size category.
@ColSmith76 suggested to re-categorize the firm size based on new establishment size.

**Comment by marenoutwater** [comment]
Just to confirm that we are not going to make adjustments in the approach at this point, but to review this at a later date.
